Document: cloudweb
Title: Debian cloudweb Manual
Author: <insert document author here>
Abstract: This manual describes what cloudweb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cloudweb/cloudweb.sgml.gz

Format: postscript
Files: /usr/share/doc/cloudweb/cloudweb.ps.gz

Format: text
Files: /usr/share/doc/cloudweb/cloudweb.text.gz

Format: HTML
Index: /usr/share/doc/cloudweb/html/index.html
Files: /usr/share/doc/cloudweb/html/*.html
